name = "PathFinder"
uuid = "06d03b12-acfb-4cd6-8e5d-a8dc42480970"
authors = ["Leoš Drahotský"]
version = "0.1.0"

[compat]
Aqua = "0.8"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]